

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ginguyenn
spring.datasource.password=nhi12354451446

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.jdbc.time_zone= UTC
spring.jpa.show-sql=true
spring.jpa.database-platform =org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.open-in-view= false

spring.sql.init.platform=h2
spring.sql.init.mode= always

spring:
    datasource:
        username:
        password:
        url:
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                #The SQL dialect makes Hibernate generate better SQL for the chosen database
                dialect: org.hibernate.dialect.PostgresSQLDialect
                jdbc:
                    timezone: UTC
        show-sql: false #set true for debugging
        database-platform: org.hibernate.dialect.PostgresSQLDialect
        hibernate:
          ddl-auto: update #(create, create-drop, validate, update)
        open-in-view: false
    sql:
        init:
            platform: postgres
            mode: always



